CREATE DATABASE db_union;

SHOW DATABASES;

USE db_union;

CREATE TABLE TB_CURSO (
	nm_genero VARCHAR(80) NOT NULL,
    nm_imagem VARCHAR(255) NOT NULL,
    ds_descricao VARCHAR(255) NOT NULL,
    nm_nome VARCHAR(80) NOT NULL,
    PRIMARY KEY (nm_genero)
);

SHOW TABLE STATUS;

SHOW COLUMNS FROM TB_CURSO;

CREATE TABLE TB_USUARIO (
	cd_usuario BIGINT NOT NULL AUTO_INCREMENT,
    nm_nome VARCHAR(80) NOT NULL,
    nm_email VARCHAR(80) NOT NULL,
    nm_senha VARCHAR(15) NOT NULL,
    PRIMARY KEY (cd_usuario)
);

SHOW COLUMNS FROM TB_USUARIO;

CREATE TABLE TB_POSTAGEM (
	cd_postagem BIGINT NOT NULL AUTO_INCREMENT,
    nm_titulo VARCHAR(80) NOT NULL,
    nm_texto VARCHAR(255) NOT NULL,
    dt_data DATE NOT NULL,
    PRIMARY KEY (cd_postagem)
);

SHOW COLUMNS FROM TB_POSTAGEM;

CREATE TABLE TB_CURSO_USUARIO (
	cd_usuario BIGINT NOT NULL,
    nm_genero VARCHAR(80) NOT NULL,
    CONSTRAINT FK_TB_CURSO_USUARIO_CD_USUARIO FOREIGN KEY (cd_usuario) REFERENCES TB_USUARIO (cd_usuario)
);

SHOW COLUMNS FROM TB_CURSO_USUARIO;

ALTER TABLE TB_CURSO_USUARIO ADD CONSTRAINT FK_TB_CURSO_USUARIO_NM_GENERO FOREIGN KEY (nm_genero) REFERENCES TB_CURSO (nm_genero);

SHOW TABLES;

CREATE TABLE TB_USUARIO_POSTAGEM (
	cd_postagem BIGINT NOT NULL,
    cd_usuario BIGINT NOT NULL,
    CONSTRAINT FK_TB_USUARIO_POSTAGEM_CD_POSTAGEM FOREIGN KEY (cd_postagem) REFERENCES TB_POSTAGEM (cd_postagem),
    CONSTRAINT FK_TB_USUARIO_POSTAGEM_CD_USUARIO FOREIGN KEY (cd_usuario) REFERENCES TB_USUARIO (cd_usuario)
);

SHOW COLUMNS FROM TB_USUARIO_POSTAGEM;